name: Sync Vue client to vue-default

on:
  push:
    paths:
      - 'client/**' # Trigger only on changes in the vue folder

jobs:
  sync-vue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Sync Vue folder to vue-default
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git clone git@github.com:WebArtWork/vue-default.git vue-default
        rm -rf vue-default/*
        cp -r client/* vue-default/
        cd vue-default
        echo "vue.webart.work" > CNAME
        git add .
        git commit -m "Update Vue files from source repository" || echo "No changes to commit"
        git push --force

    - name: Clean up SSH
      run: |
        rm -f ~/.ssh/id_rsa
        rm -f ~/.ssh/known_hosts
